server:
  port: 8888


security:
  base:
    enabled: true


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?autoReconnect=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:dao/*.xml